# Generated by Django 4.1.1 on 2022-09-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_razao_social', models.CharField(max_length=100, verbose_name='Razão social')),
                ('fornecedor_cpf_cnpj', models.CharField(max_length=20, verbose_name='CPFJ/CNPJ')),
                ('fornecedor_email', models.CharField(max_length=100, verbose_name='Email')),
                ('fornecedor_telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('fornecedor_logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('fornecedor_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('fornecedor_numero', models.IntegerField(default=0, verbose_name='Número')),
                ('fornecedor_cep', models.IntegerField(default=0, verbose_name='CEP')),
                ('fornecedor_complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('fornecedor_obs', models.CharField(default='', max_length=100, verbose_name='Observações')),
                ('fornecedor_ativo', models.CharField(max_length=1)),
                ('fornecedor_cidade_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.cidades', verbose_name='Cidade_ID')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['fornecedor_razao_social', 'fornecedor_cpf_cnpj'],
            },
        ),
    ]
