# Generated by Django 4.1.1 on 2022-10-04 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_nome', models.CharField(max_length=50)),
                ('estado_uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['estado_nome', 'estado_uf'],
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_nome', models.CharField(max_length=100, verbose_name='Cidade')),
                ('cidade_cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade_ativo', models.CharField(max_length=1)),
                ('cidade_estado', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='endereco.estados')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['cidade_nome', 'cidade_cep'],
            },
        ),
    ]
