# Generated by Django 4.1.1 on 2022-09-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_data_pedido', models.DateField(verbose_name='Data do pedido')),
                ('pedido_prazo_entrega', models.DateField(verbose_name='Prazo da entrega')),
                ('pedido_obs', models.CharField(max_length=100, verbose_name='Observações')),
                ('pedido_ativo', models.CharField(max_length=1)),
                ('pedido_cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Cliente_ID')),
                ('pedido_fornecedor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedores', verbose_name='Fornecedor_ID')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['pedido_data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Itensped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itensped_qtde', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('itensped_ativo', models.CharField(max_length=1)),
                ('itensped_produto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produtos', verbose_name='Produto_ID')),
            ],
            options={
                'verbose_name': 'Itens do pedido',
                'verbose_name_plural': 'Item do pedido',
                'ordering': ['itensped_qtde'],
            },
        ),
    ]
