# Generated by Django 4.1.1 on 2022-10-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fornecedores',
            field=models.ManyToManyField(related_name='pedidos', to='fornecedores.fornecedores'),
        ),
    ]
