# Generated by Django 4.1.1 on 2022-10-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_fornecedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.FloatField(default=0),
        ),
    ]
