# Generated by Django 4.1.1 on 2022-10-04 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('fornecedor_cpf_cnpj', models.CharField(max_length=20, verbose_name='CPFJ/CNPJ')),
                ('fornecedor_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('fornecedor_telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('fornecedor_logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('fornecedor_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('fornecedor_numero', models.IntegerField(default=0, verbose_name='Número')),
                ('fornecedor_cep', models.IntegerField(default=0, verbose_name='CEP')),
                ('fornecedor_complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('fornecedor_ativo', models.CharField(max_length=1)),
                ('fornecedor_criem', models.DateTimeField(auto_now_add=True)),
                ('fornecedor_cripor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['fornecedor_nome'],
            },
        ),
    ]
