# Generated by Django 4.1.1 on 2022-10-13 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_alter_cidades_options_remove_cidades_cidade_cep'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedores',
            name='fornecedor_cpf_cnpj',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fornecedor_cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='endereco.cidades', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fornecedor_cnpj',
            field=models.CharField(default=0, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fornecedor_obs',
            field=models.CharField(default=0, max_length=100, verbose_name='Obs'),
        ),
    ]
