# Generated by Django 4.1.1 on 2022-10-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_options_and_more'),
        ('fornecedores', '0002_alter_fornecedores_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedores',
            options={'ordering': ['razao'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.RenameField(
            model_name='fornecedores',
            old_name='fornecedor_ativo',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='fornecedores',
            old_name='fornecedor_criem',
            new_name='criem',
        ),
        migrations.RenameField(
            model_name='fornecedores',
            old_name='fornecedor_razao',
            new_name='razao',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='fornecedor_cripor',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(default=1, max_length=20, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='cripor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Fornecedor', to='usuarios.perfil'),
            preserve_default=False,
        ),
    ]
