# Generated by Django 4.1 on 2022-08-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidades',
            options={'ordering': ['cidade_nome', 'Cidade_cep'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.RenameField(
            model_name='cidades',
            old_name='Cidade_nome',
            new_name='cidade_nome',
        ),
    ]
