# Generated by Django 4.1 on 2022-08-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_cidades_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidades',
            options={'ordering': ['cidade_nome', 'cidade_cep'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.RenameField(
            model_name='cidades',
            old_name='Cidade_ativo',
            new_name='cidade_ativo',
        ),
        migrations.RenameField(
            model_name='cidades',
            old_name='Cidade_cep',
            new_name='cidade_cep',
        ),
    ]
