# Generated by Django 4.1 on 2022-08-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_fornecedores_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['cliente_nome', 'cliente_telefone'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_ativo',
            new_name='cliente_ativo',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_bairro',
            new_name='cliente_bairro',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_cep',
            new_name='cliente_cep',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_cidade_id',
            new_name='cliente_cidade_id',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_complemento',
            new_name='cliente_complemento',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_cpf',
            new_name='cliente_cpf',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_logradouro',
            new_name='cliente_logradouro',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_nome',
            new_name='cliente_nome',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_numero',
            new_name='cliente_numero',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_obs',
            new_name='cliente_obs',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Cliente_telefone',
            new_name='cliente_telefone',
        ),
    ]
