# Generated by Django 4.1 on 2022-08-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segmentos',
            options={'ordering': ['segmento_nome'], 'verbose_name': 'Segmento', 'verbose_name_plural': 'Segmentos'},
        ),
        migrations.RenameField(
            model_name='segmentos',
            old_name='Segmento_ativo',
            new_name='segmento_ativo',
        ),
        migrations.RenameField(
            model_name='segmentos',
            old_name='Segmento_nome',
            new_name='segmento_nome',
        ),
    ]
