# Generated by Django 4.1 on 2022-08-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_segmentos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['produto_nome', 'produto_descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='Produto_ativo',
            new_name='produto_ativo',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='Produto_descricao',
            new_name='produto_descricao',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='Produto_nome',
            new_name='produto_nome',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='Produto_qtde',
            new_name='produto_qtde',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='Produto_segmento_id',
            new_name='produto_segmento_id',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='Produto_valor_unit',
            new_name='produto_valor_unit',
        ),
    ]
