# Generated by Django 4.1 on 2022-08-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_produtos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'ordering': ['pedido_data_pedido'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='Pedido_ativo',
            new_name='pedido_ativo',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='Pedido_cliente_id',
            new_name='pedido_cliente_id',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='Pedido_data_pedido',
            new_name='pedido_data_pedido',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='Pedido_fornecedor_id',
            new_name='pedido_fornecedor_id',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='Pedido_obs',
            new_name='pedido_obs',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='Pedido_prazo_entrega',
            new_name='pedido_prazo_entrega',
        ),
    ]
