# Generated by Django 4.1 on 2022-08-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_pedidos_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
        migrations.AlterModelOptions(
            name='itensped',
            options={'ordering': ['itensped_qtde'], 'verbose_name': 'Itens do pedido', 'verbose_name_plural': 'Item do pedido'},
        ),
        migrations.RenameField(
            model_name='itensped',
            old_name='Itensped_ativo',
            new_name='itensped_ativo',
        ),
        migrations.RenameField(
            model_name='itensped',
            old_name='Itensped_produto_id',
            new_name='itensped_produto_id',
        ),
        migrations.RenameField(
            model_name='itensped',
            old_name='Itensped_qtde',
            new_name='itensped_qtde',
        ),
    ]
