# Generated by Django 4.1 on 2022-08-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_delete_teste_alter_itensped_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidades',
            name='cidade_cep',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cliente_cidade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.cidades', verbose_name='Cidade_ID'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cliente_cpf',
            field=models.CharField(max_length=100, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='fornecedor_cpf_cnpj',
            field=models.CharField(max_length=20, verbose_name='CPFJ/CNPJ'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='fornecedor_telefone',
            field=models.CharField(max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='itensped',
            name='itensped_produto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.produtos', verbose_name='Produto_ID'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedido_cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.clientes', verbose_name='Cliente_ID'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedido_data_pedido',
            field=models.DateField(verbose_name='Data do pedido'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedido_fornecedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.fornecedores', verbose_name='Fornecedor_ID'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedido_prazo_entrega',
            field=models.DateField(verbose_name='Prazo da entrega'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='produto_segmento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.segmentos', verbose_name='Segmento_ID'),
        ),
    ]
