# Generated by Django 4.1 on 2022-09-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_cidades_cidade_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cliente_email',
            field=models.CharField(default='', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
