# Generated by Django 4.1 on 2022-09-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_clientes_cliente_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='fornecedor_contato',
            new_name='fornecedor_email',
        ),
    ]
