# Generated by Django 4.1.1 on 2022-10-10 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endereco', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_bairro',
            field=models.CharField(default='none', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_cep',
            field=models.IntegerField(default=0, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_cidade_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='endereco.cidades', verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_complemento',
            field=models.CharField(default='none', max_length=100, verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_cpf_cnpj',
            field=models.CharField(default=1, max_length=20, verbose_name='CPFJ/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_email',
            field=models.EmailField(default='none', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_logradouro',
            field=models.CharField(default='none', max_length=100, verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_telefone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='perfil_nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='perfil_sobrenome',
            field=models.CharField(max_length=50, null=True, verbose_name='Sobrenome'),
        ),
    ]
