# Generated by Django 4.1.1 on 2022-10-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_nome',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_sobrenome',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
    ]
