# Generated by Django 4.1.1 on 2022-10-11 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_remove_perfil_telefone_remove_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nome'], 'verbose_name': 'Nome'},
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_cep',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_cidade_id',
            new_name='cidade_id',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_complemento',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_logradouro',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_numero',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_sobrenome',
            new_name='sobrenome',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil_telefone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
