# Generated by Django 4.1.1 on 2022-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nome'], 'verbose_name': 'Perfil'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='nome'),
        ),
    ]
