# Generated by Django 4.1.1 on 2022-10-13 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endereco', '0001_initial'),
        ('usuarios', '0004_alter_perfil_options_alter_perfil_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cidade_id',
            field=models.ForeignKey(null=0, on_delete=django.db.models.deletion.PROTECT, to='endereco.cidades', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(null=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
