# Generated by Django 4.1.1 on 2022-09-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cliente_telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cliente_cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('cliente_email', models.CharField(max_length=100, verbose_name='Email')),
                ('cliente_logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('cliente_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cliente_numero', models.IntegerField(default=0, verbose_name='Número')),
                ('cliente_cep', models.IntegerField(default=0, verbose_name='CEP')),
                ('cliente_complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('cliente_obs', models.CharField(max_length=100, verbose_name='Observações')),
                ('cliente_ativo', models.CharField(max_length=1)),
                ('cliente_cidade_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.cidades', verbose_name='Cidade_ID')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['cliente_nome', 'cliente_telefone'],
            },
        ),
    ]
