# Generated by Django 4.1.1 on 2022-10-10 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['cliente_apelido'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='cliente_nome',
            new_name='cliente_apelido',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_bairro',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_cep',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_cidade_id',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_complemento',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_cpf',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_logradouro',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_numero',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_obs',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_telefone',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_criem',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_cripor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='usuarios.perfil'),
            preserve_default=False,
        ),
    ]
