# Generated by Django 4.1.1 on 2022-09-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cliente_email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
