# Generated by Django 4.1.1 on 2022-10-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('ativo', models.CharField(max_length=1)),
                ('criem', models.DateTimeField(auto_now_add=True)),
                ('cripor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consumidor', to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Consumidor',
                'verbose_name_plural': 'Consumidores',
                'ordering': ['apelido'],
            },
        ),
    ]
